### ISSUE TITLE
Default command

### ISSUE THREAD

**Issue by defunkt** [rtomayko/ronn#14]
While I appreciate the elegance of running `ronn FILE` and having roff or whatever printed to the terminal, I think the more useful default command would be this:

```
ronn -b5 FILE
```

That is, `-b5` was assumed. Because when I run that, and I see `ronn` has taken my `.markdown` or `.ronn` file and converted it into a beautiful page, I already like this new tool and I think we may have a future together.

Because that is how I felt when I discovered `-b5`.

Anyway, I think that should be the default.

**Comment by rtomayko** [comment]
Yeah. I liked that about docco actually. It makes it a bit easier to experiment when your just starting out.

**Comment by rtomayko** [comment]
ronn(1) builds html/roff files by default; closed by 1d6bad06129e242792cfa108f0f614eef87632b8
