### ISSUE TITLE
Escaping of chars between < >

### ISSUE THREAD

**Issue by unexist** [rtomayko/ronn#15]
Since 0.4 ronn escapes the letters between < > and the result looks like garbage in manpages. Maybe this is caused by rdiscount, but still it's not what I expect to see in a manpage.

Example:

% cat foo.1.ron

<pre>
## Foobar

Random junk

## Bugreport

Report bugs to &lt;dummy@email.com&gt;
</pre>

% cat foo.1

<pre><code>
.\" generated with Ronn/v0.4.1
.\" http://github.com/rtomayko/ronn/
.
.TH "FOO" "1" "March 2010" "" ""
.
.SH "NAME"
\fBfoo\fR \-\-
.
.SH "Foobar"
Random junk
.
.SH "Bugreport"
Report bugs to \fI&amp;#100;&amp;#x75;&amp;#109;&amp;#x6d;&amp;#x79;&amp;#64;&amp;#x65;&amp;#109;&amp;#97;&amp;#x69;&amp;#x6c;&amp;#46;&amp;#99;&amp;#x6f;&amp;#109;\fR
</code></pre>

**Comment by rtomayko** [comment]
oh yeah. that's markdown's silly email obfuscation nonsense. Thanks for the report. I have a few other roff issues to fix and I'll get a release out.

**Comment by rcrowley** [comment]
I second this report and eagerly anticipate the next version.

**Comment by rtomayko** [comment]
decode dec and hex HTML entities in roff output; closed by 4465f24e0454d61030acc2cb742398c3152acee7
