### ISSUE TITLE
don't include markdown(5) or rename

### ISSUE THREAD

**Issue by dcampbell24** [rtomayko/ronn#18]
While it is nice to have a manpage for markdown, only a markdown implementation should have a markdown manpage. This is just asking for name/file clashses. Maybe, include it with ronn(7) or ronn(5).

**Comment by rtomayko** [comment]
I'd hate to include all that in `ronn(7)`. Maybe I'll ship the `markdown(5)` manpage that ships with Discount with RDiscount, since that's a dependency of ronn.

**Comment by rtomayko** [comment]
rdiscount now ships with `markdown(7)` from [discount](http://www.pell.portland.or.us/~orc/Code/discount/) and the ronn manpages reference it.
