### ISSUE TITLE
name field should have only one dash

### ISSUE THREAD

**Issue by sunaku** [rtomayko/ronn#20]
All the manpages I see in Linux have only one dash separating the subject from the tagline:

```
man - an interface to the on-line reference manuals
cat - concatenate files and print on the standard output
sh - shell, the standard command language interpreter
```

But Ronn 0.5 forces two dashes (even if I write a single dash).  Shouldn't it follow prior convention?

**Comment by rtomayko** [comment]
Yes, it should. The first series of one or more dashes should delimit the subject from the tagline.

I'm planning on spending some time in here over the weekend or maybe sometime next week. This is a quick and easy fix.

**Comment by sunaku** [comment]
I've implemented this in my fork and hope this saves you some time:
http://github.com/sunaku/ronn

Cheers.

**Comment by rtomayko** [comment]
[Merged.](http://github.com/rtomayko/ronn/compare/b1e35a74%5E...9de06ed6). Thanks.

The `h1` now must match `/.*-+/`.
