### ISSUE TITLE
single quotes should be escaped in generated man page

### ISSUE THREAD

**Issue by kapouer** [rtomayko/ronn#21]
single quotes should appear as \'
or else man thinks it's a macro.

**Comment by kapouer** [comment]
i meant \'

**Comment by rtomayko** [comment]
Oh? Weird. I didn't realize that. We have to escape `-` characters too, so this should be easy to plug into the same place.

**Comment by kapouer** [comment]
Single quotes AND dots should be escaped when they start a new line.
I also have trouble with lines starting with multiple dots, even when escaped.

**Comment by kapouer** [comment]
for example, double dots should be escaped like this : \\.\.

**Comment by kapouer** [comment]
i have trouble with man page syntax... it seems multiple dots at the beginning of a file can't really be escaped. Using aforementioned way does not work. I finally had success with adding a space before the dots, i.e. " \.\.\."
Also note that you can test if syntax is correct on file toto.1 :
LANG=C MANWIDTH=80 man --warnings -E UTF-8 -l toto.1 >/dev/null

**Comment by rtomayko** [comment]
All of `[\\-'".]` are backslash escaped as of 6a410d9428e03cb9b3f66fe985e384c461765155. I also added `-w` option to ronn for enabling warnings from groff when building or viewing.

**Comment by kapouer** [comment]
Nice, i also figured how to escape dots at the start of a newline :
/^./ shall become "\|."
That way multiple dots won't trigger groff warnings.

**Comment by smira** [comment]
It seems that escaping `'` as `\'` is not correct: `\'` is different symbol which might be not rendered correctly on terminal.

From groff man page:

```
\'

The acute accent '; same as \(aa. Unescaped: apostrophe, right quotation mark, single quote (ASCII 0x27).
```

Single quote should be `\(cq`.
