### ISSUE TITLE
Make man section TOC optional

### ISSUE THREAD

**Issue by rtomayko** [rtomayko/ronn#24]
There's now a right-side TOC included by default in HTML output, [courtesy of sunaku](http://github.com/rtomayko/ronn/commit/aaa91c1b). [Example here](http://snk.tuxfamily.org/lib/ember/).

I'd like to add an option to the `ronn` command that would disable this for the simple, non-TOC display. 

There's also some issues with page width, especially with code examples and preformatted blocks. I'd like to consider using a non-fixed layout and maybe moving it over to the left. The [man.cx layout](http://man.cx/dash) and [node.js manual](http://nodejs.org/api.html) are good examples of what alternative takes on a TOC.

For now, we ought to get a basic option in for turning the TOC off and then we can address some of the other stuff with custom layouts when that lands.

**Comment by sunaku** [comment]
Wow, the node.js manual is amazing!   Looking forward to getting that style into Ronn.  If we do a good job, hopefully node.js will use Ronn for its manual.

**Comment by noonat** [comment]
Node does use ronn for it's manual. It just does its own header and footer for formatting.

**Comment by rtomayko** [comment]
There's a new scheme for managing multiple CSS stylesheets on master now. I moved the TOC css out into a separate `toc.css` file. You enable it by pass `-s toc` or `--style=toc` to `ronn`.
