### ISSUE TITLE
automatically link cross-references "See <SECTION>"

### ISSUE THREAD

**Issue by sunaku** [rtomayko/ronn#25]
On April 18, 2010, evaryont wrote:
A request based off this: What about detecting headings and providing links to them throughout the document? I just notice a lot of "See CONFIGURATION", so having CONFIGURATION link to the proper heading would be great. To do so would require keeping a list of all the headings, then doing a gsub(/FOO/, "<a href='#FOO'>FOO</a>).

**Comment by nogweii** [comment]
Now that there is a TOC, half of this is already solved (remembering the headers). Now ronn just needs to find them in the text itself, and link them.

More linking: issue #28

**Comment by rtomayko** [comment]
You can now link to any section with the `[SEE ALSO][]` syntax. We create markdown reference links for all level 2 and 3 headings.

It's not as terse as just assuming all caps, but it's not magic either :)
