### ISSUE TITLE
Move TOC to left

### ISSUE THREAD

**Issue by rtomayko** [rtomayko/ronn#27]
I'm pretty sure the TOC should be on the left in the default layout. The problem I'm having is that it makes it really hard to create a decent right margin. This is basically what it looks like right now:

![tight](http://img.skitch.com/20100426-p3x6771ngfy9ku3j3g281uiksx.png)

The right margin feels way too tight because of the 8ex indent on the left. When I try to open it up, it looks a little better but throws off the consistent alignment of the heading elements:

![gap](http://img.skitch.com/20100426-edidxeaxyqa35n3g5mdcje9pxb.png)

If we move it to the left, the problem goes away, although its possible other things won't work right in that config. For instance, I think the left-aligned text in the TOC looks great flush against the manpage right edge.

**Comment by defunkt** [comment]
I like it on the right.

**Comment by rtomayko** [comment]
Going with it on the right then.
