### ISSUE TITLE
Integrate links to man.cx

### ISSUE THREAD

**Issue by nogweii** [rtomayko/ronn#28]
Here's an idea: in the HTML output, why not match `/\w+\(\d\)/` and link to that man on man.cx? (Like what man.cx already does, see [dash(1) 'SEE ALSO'](http://man.cx/dash#sec7))

**Comment by nogweii** [comment]
Of course, that regular expression shouldn't be used, as sections can be `3p` (for Perl libraries) or other variations. (I remember seeing a `1x` section on my system before)

**Comment by rtomayko** [comment]
As of 0.7.0, you can include an `index.txt` and define links for any manual references. In the future, I may add a command line option to generate the index and fill in man.cx links for any references that aren't already defined.
