### ISSUE TITLE
Duplicate html output

### ISSUE THREAD

**Issue by tj** [rtomayko/ronn#29]
I am just using:

```
docs/api.html: docs/api.md
ronn -5 --html $< > $@
```

however its outputting the page twice in the same api.html file

**Comment by rtomayko** [comment]
Ha! I guess the args are driving output. Just use `-5` or `--html` but not both (they're the same arg).

**Comment by tj** [comment]
I ended up going with custom header/footer with `--fragment` anyways thanks!
