### ISSUE TITLE
Spaces between underlines/anglebrackets and parameter are eaten

### ISSUE THREAD

**Issue by adamv** [rtomayko/ronn#31]
See: http://gist.github.com/436893

**Comment by adamv** [comment]
Added (non-passing) regression test; also, ignore ".wrong" files for failed tests.

http://github.com/adamv/ronn/tree/missing_spaces

**Comment by rtomayko** [comment]
fix roff spacing between inline sibling elements closed by 44c19001dc40ebfa1ff0d77e5ef6b0effe82b2e9

**Comment by rtomayko** [comment]
0.6.6 gem is out. Sorry about that and thanks for the patch.

**Comment by adamv** [comment]
Thanks for the fix!
