### ISSUE TITLE
ronn fails to generate code block containing doublequote (") character

### ISSUE THREAD

**Issue by pawelz** [rtomayko/ronn#33]
Just try to generate manpage from the following file:
    t(1) - test
    ===========

```
## test

    [ "$11" ]
```

Note that, html is generated correctly.

**Comment by pawelz** [comment]
Just noticed - it does not like doublequotes at all, not only in code blocks.

**Comment by rtomayko** [comment]
fix quote escapes destroying roff output, closed by 7931647d4a4178198941e9cfff87fbe8bc9d6a03

**Comment by rtomayko** [comment]
Not sure how I missed that. Thanks for the report!

**Comment by pawelz** [comment]
Thanks for fixing it.
