### ISSUE TITLE
Allow `page`(section) to work with link indexes

### ISSUE THREAD

**Issue by rcrowley** [rtomayko/ronn#40]
I like to write references to other manual pages as `page`(section) because this comes closest in both raw Markdown (as seen on GitHub) and non-linked Roff output to the visual style of most standard manual pages.  Specifically, that the page name is shown bold (or in my terminal's case, colored) and the section is not.

Desired: http://devstructure.github.com/contractor/blueprint-create.1.html
Close, but no cigar: http://devstructure.github.com/doubledown/doubledown.1.html

**Comment by rcrowley** [comment]
http://github.com/rcrowley/ronn/tree/backticks includes a fix.

**Comment by rtomayko** [comment]
I really like that formatting too. I think we should go another step and make it always display like your preferred style whether backticks are used or not.

**Comment by rcrowley** [comment]
I felt that was a bit presumptuous for me to do but now that you're the one suggesting it, I can agree wholeheartedly.

**Comment by rtomayko** [comment]
Merged. I'll get it to format consistency regardless of source markup before the next release.
