### ISSUE TITLE
Suppress hyphenation in back-tick blocks

### ISSUE THREAD

**Issue by adamv** [rtomayko/ronn#54]
I'm using a back-tick block to show a command line, like `brew --version`, but man is doing a break in the middle of `--version`. It is possible to suppress hyphenation (but not word breaks) in these blocks?

**Comment by aherrmann** [comment]
Hi, I think I'm having a similar issue. When including a link, which doesn't fit in one line, it will be broken and hyphenated.  Unfortunately, backticks won't change that. Thus, neither right click -> open link, nor copy paste to browser's location bar work without extra effort.
