### ISSUE TITLE
anchors on level one and two headings

### ISSUE THREAD

**Issue by rtomayko** [rtomayko/ronn#6]
I should be able to go to `manpage.html#OPTIONS`.

**Comment by nogweii** [comment]
I think this one is mostly done already, no? Only thing I see missing is the id attribute to NAME.

A request based off this: What about detecting headings and providing links to them throughout the document? I just notice a lot of "See CONFIGURATION", so having CONFIGURATION link to the proper heading would be great. To do so would require keeping a list of all the headings, then doing a `gsub(/FOO/, "<a href='#FOO'>FOO</a>)`.

**Comment by sunaku** [comment]
I have implemented the original request in my fork: sunaku/ronn@267c22b37f72f7ae63a76ef888cee2a95533a6df

**Comment by rtomayko** [comment]
Merged. Thanks!
