### ISSUE TITLE
meta utf8 in html is bad

### ISSUE THREAD

**Issue by pastjean** [rtomayko/ronn#62]
In the generated documents the header contains:

```
<meta http-equiv='content-type' value='text/html;charset=utf8'>
```

it should be:

```
<meta http-equiv='content-type' content='text/html;charset=utf8'>
# content vs value
```

This makes browser generate bad characters for the extended characters like "é è à ..."

This bug is not present when ronn is ran in server mode "-S" option

**Comment by gandaro** [comment]
Please have a look at #60, I have already fixed that on my fork.

**Comment by pastjean** [comment]
ok ! thank you! I was only looking for "utf8" in issues and pull resquest
