### ISSUE TITLE
Publish to rubyforge

### ISSUE THREAD

**Issue by tmpfs** [rtomayko/ronn#74]
Hey,

I recently upgraded ruby with rvm and did a gemset copy and have lost the changes I implemented as patches (it makes the gemset pristine), symbolic linking to the ronn executable in my local repository does not appear to work.

Would you be so kind as to publish an updated gem?

Cheers!

**Comment by rtomayko** [comment]
Yes. Apologies, I haven't had much time to deal with OSS stuff recently. I'll get a release out ASAP.

**Comment by tmpfs** [comment]
No worries, thanks for merging the other pull request :)

**Comment by ghedo** [comment]
Is there any news about this?

**Comment by tmpfs** [comment]
Closing as well it's been so long and I no longer use ronn(1).
