### ISSUE TITLE
Output man pages without *.roff extensions

### ISSUE THREAD

**Issue by jviotti** [rtomayko/ronn#85]
Npm expects man pages listed on `package.json` to not have a `*.roff` extension and [fails otherwise](https://github.com/npm/npm/issues/7000).

Is there an easy way to prevent the extension from being added without having to rename the files programatically, using `ronn --build --roff doc/*.md`?

**Comment by apjanke** [comment]
Looks like this has been addressed: the roff output files no just have the `.1`/`.2`/etc extension, and not `.roff`. Are you still having trouble with this?

**Comment by jviotti** [comment]
Closing stale issues
