### ISSUE TITLE
Paragraph in source not in output

### ISSUE THREAD

**Issue by denisdefreyne** [rtomayko/ronn#9]
When running the following example through ron, the middle paragraph (“Always use…”) is ommited from the output. This happens with both manpage output as HTML output.

```
test(1) -- just a ron test
==========================

## TEST

Foo

Always use `attr_reader`, `attr_writer` or `attr_accessor`. Do not use `for...in`; use each instead. Do not use `and`/`or`; use `&&`/`||` instead.

Bar
```

This results in a HTML page or man page that looks somewhat like this:

```
TEST
        Foo

        Bar
```

When leaving out the last paragraph (Bar), the missing paragraph turns up.

**Comment by rtomayko** [comment]
Weird. I'll be sure to take a look at this soon. Thanks for the solid test case.

**Comment by rtomayko** [comment]
Can you check to see if this is still an issue with the current master? I can't seem to reproduce it.

**Comment by denisdefreyne** [comment]
I can no longer reproduce this issue. Thanks for taking a look!
